version: "3"
services:
  spring_test:
    container_name: spring_test
    build: ./xyz
    ports:
      - "8083:8081"
    volumes:
      - /spring_test:/image
    restart: on-failure
  spring_chat_first:
    container_name: spring_chat_first
    build: ./xyz-chat
    ports:
      - "8089:8080"
    volumes:
      - /spring_chat_first:/image
    restart: on-failure
  spring_chat_second:
    container_name: spring_chat_second
    build: ./xyz-chat
    ports:
      - "8088:8080"
    volumes:
      - /spring_chat_second:/image
    restart: on-failure  
