import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Header";
import TabBar from "@/components/TabBar";

export const metadata = {
  title: "XYZ",
  description: "Generated by create next app",
};

const pixelFont = localFont({
  src: "../assets/font/NeoDunggeunmoPro-Regular.woff",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pixelFont.className}>
      <body className="h-screen">
        <Header />
        <main className="pt-16 px-5">{children}</main>
        <TabBar />
      </body>
    </html>
  );
}
