import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "XYZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <main className="pt-16 px-5">{children}</main>
      </body>
    </html>
  );
}
